name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: sqlalchemy-modelgen
      uses: shree14/sqlalchemy-modelgen@main
      with:
        python-version: 3.8
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest discover tests
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
